/**
 * fcm.js — Thin wrapper around Firebase Admin (Cloud Messaging).
 *
 * This is what actually wakes up the Android app when it's backgrounded or
 * fully closed: Web Push (web-push / VAPID, see webpush.js) depends on the
 * browser's Push API, which Android's WebView (used by the Capacitor wrapper
 * in mobile/) does not reliably deliver in the background. FCM uses Google
 * Play Services instead, so it works even with the app killed.
 *
 * Requires ONE of the following environment variables (set in server/.env):
 *
 *   FIREBASE_SERVICE_ACCOUNT_JSON    — the full service account JSON, as a
 *                                       single-line string
 *   FIREBASE_SERVICE_ACCOUNT_BASE64  — the same JSON, base64-encoded
 *                                       (handy when the platform's env var
 *                                       editor mangles raw JSON/newlines)
 *
 * Get this file from: Firebase Console → Project settings → Service accounts
 *   → Generate new private key. The Firebase project must have an Android
 * app registered with appId "com.socialbattery.app" (see mobile/capacitor.config.json)
 * and mobile/android/app/google-services.json must come from that same project.
 */

let admin = null;
let configured = false;
let app = null;

function init() {
  if (configured) return;
  configured = true;

  try {
    admin = require('firebase-admin');
  } catch {
    console.warn('[fcm] firebase-admin not installed — FCM push disabled. Run: npm install');
    return;
  }

  const rawJson = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  const rawBase64 = process.env.FIREBASE_SERVICE_ACCOUNT_BASE64;

  if (!rawJson && !rawBase64) {
    console.warn('[fcm] FIREBASE_SERVICE_ACCOUNT_JSON / FIREBASE_SERVICE_ACCOUNT_BASE64 not set — FCM push disabled.');
    admin = null;
    return;
  }

  try {
    const jsonStr = rawJson || Buffer.from(rawBase64, 'base64').toString('utf8');
    const serviceAccount = JSON.parse(jsonStr);
    app = admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
    });
  } catch (err) {
    console.warn('[fcm] failed to parse/init Firebase service account:', err.message);
    admin = null;
  }
}

/**
 * Send an FCM data+notification message to a list of device tokens.
 *
 * @param {string[]} tokens
 * @param {{ title: string, body: string, url?: string, tag?: string }} payload
 * @returns {Promise<{ successTokens: string[], invalidTokens: string[] }>}
 */
async function sendFcmToTokens(tokens, payload) {
  init();
  if (!admin || !app || !tokens?.length) return { successTokens: [], invalidTokens: [] };

  const message = {
    tokens,
    notification: {
      title: payload.title || 'SocialBattery',
      body: payload.body || '',
    },
    data: {
      url: payload.url || '/community',
      tag: payload.tag || 'community-event',
    },
    android: {
      priority: 'high',
      notification: {
        // No custom `icon` here on purpose: it must reference a drawable
        // bundled in mobile/android/app/src/main/res, which doesn't exist
        // yet (mobile/android/ is generated by `npx cap add android` and is
        // gitignored) — an icon name that doesn't resolve makes Android
        // silently drop the notification. Falls back to the app's launcher
        // icon. channelId must match one created client-side (see
        // client/src/lib/capacitorPush.js createChannel) or Android 8+
        // silently drops the notification too.
        channelId: 'default',
        color: '#7c3aed',
      },
    },
    apns: {
      payload: { aps: { sound: 'default' } },
    },
  };

  try {
    const resp = await admin.messaging(app).sendEachForMulticast(message);
    const successTokens = [];
    const invalidTokens = [];

    resp.responses.forEach((r, i) => {
      if (r.success) {
        successTokens.push(tokens[i]);
      } else {
        const code = r.error?.code || '';
        // These codes mean the token is dead and should be removed —
        // anything else (rate limits, transient network errors) is left
        // alone so we don't nuke a token over a temporary hiccup.
        if (
          code === 'messaging/registration-token-not-registered' ||
          code === 'messaging/invalid-registration-token' ||
          code === 'messaging/invalid-argument'
        ) {
          invalidTokens.push(tokens[i]);
        }
      }
    });

    return { successTokens, invalidTokens };
  } catch (err) {
    console.warn('[fcm] sendEachForMulticast error:', err.message);
    return { successTokens: [], invalidTokens: [] };
  }
}

module.exports = { sendFcmToTokens };
