name: Actualizar Google Sheet

on:
  schedule:
    - cron: '*/30 * * * *'  # cada 30 minutos (puedes cambiarlo)
  workflow_dispatch:        # permite ejecutarlo manualmente desde GitHub

jobs:
  update_excel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Descargar datos desde Google Sheets como CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTmbgLgN6Jd460AsuM2NSKwG347DtTQzPiyn-8gGxqWHG0Es69m-mnOFKQmuGZAdw/pub?output=csv" -o datos.csv

      - name: Commit y push si hay cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add datos.csv
          git diff-index --quiet HEAD || git commit -m "Actualizar datos desde Google Sheets"
          git push
